name: Sync

permissions:
  contents: read

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: mirror-main
  cancel-in-progress: false

jobs:
  sync-gitee:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: main

        - name: Mirror to Gitee
          uses: yesolutions/mirror-action@662fce0eced8996f64d7fa264d76cddd84827f33
          with:
            REMOTE: 'https://gitee.com/opguess/idv-login.git'
            GIT_USERNAME: opguess
            GIT_PASSWORD: ${{ secrets.GITEE_TOKEN }}

  sync-gitea:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: main

        - name: Mirror main to Gitea
          uses: yesolutions/mirror-action@662fce0eced8996f64d7fa264d76cddd84827f33
          with:
            REMOTE: 'https://git.keygen.eu.org/keygen/idv-login.git'
            GIT_USERNAME: keygen
            GIT_PASSWORD: ${{ secrets.GITEA_API_TOKEN }}
            PUSH_ALL_REFS: 'false'
            GIT_REF: 'refs/heads/main'
            GIT_PUSH_ARGS: '--verbose'
